config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  resources :registered_applications
  devise_for :users
  root 'registered_applications#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application, optional: true
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_access_control_headers 

     def set_access_control_headers
       puts "does this run"
       headers['Access-Control-Allow-Origin'] = '*'
       headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
       headers['Access-Control-Allow-Headers'] = 'Content-Type'
     end


  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    end

    @event = registered_application.event.new(event_params)
    if @event.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end

  end

  def preflight
    head 200
  end


  private
     def event_params
       params.require(:event).permit(:name)
     end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_apps = RegisteredApplication.all
  end

  def show
    @registered_apps = RegisteredApplication.find(params[:id])
    @events = @registered_apps.event.group_by(&:name)
  end

  def new
    @registered_apps = RegisteredApplication.new
  end

  def edit
      @registered_apps = RegisteredApplication.find(params[:id])
  end

  def update
      p params
      @registered_apps = RegisteredApplication.find(params[:id])
      @registered_apps.title = params[:registered_application][:title]
      @registered_apps.url = params[:registered_application][:url]
      @registered_apps.user_id = current_user.id

      if @registered_apps.save
        flash[:notice] = "Registered application was saved."
        redirect_to registered_applications_path
      else
        flash.now[:alert] = "There was an error saving the registered application. Please try again."
        render :new
      end
  end

  def create
    p params
    @registered_apps = RegisteredApplication.new
    @registered_apps.title = params[:registered_application][:title]
    @registered_apps.url = params[:registered_application][:url]
    @registered_apps.user_id = current_user.id

    if @registered_apps.save
      flash[:notice] = "Registered application was saved."
      redirect_to registered_applications_path
    else
      flash.now[:alert] = "There was an error saving the registered application. Please try again."
      render :new
    end
  end

  def destroy
    p params
    @registered_apps = RegisteredApplication.find(params[:id])

    if @registered_apps.destroy
     flash[:notice] = "\"#{@registered_apps.title}\" was deleted successfully."
     redirect_to registered_applications_path
    else
     flash.now[:alert] = "There was an error deleting the post."
     render :show
    end

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/registered_applications/edit.html.erb
<h1>RegisteredApplications#edit</h1>
<p>Find me in app/views/registered_applications/edit.html.erb</p>

<h1>Edit Post</h1>

 <div class="row">

   <div class="col-md-8">
     <%= form_for @registered_apps do |f| %>

       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
       </div>

       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_field :url, rows: 8, class: 'form-control', placeholder: "Enter url" %>
       </div>

       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>

     <% end %>


   </div>

 </div>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h2>



    <div class="container">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Application</th>
            <th>URL</th>
          </tr>
        </thead>

          <tbody>
              <% @registered_apps.each do |app| %>
            <tr>
              <td>
                <h4 class="media-heading">
                  <%= link_to app.title, app %>
                </h4>
              </td>
              <td>
                <h4 class="media-heading">
                  <%= app.url %>
                </h4>
              </td>
            </tr>
              <% end %>
          </tbody>
        </table>
      </div>

      <%= link_to "Register an Application", new_registered_application_path, class: 'btn btn-primary' %>

app/views/registered_applications/new.html.erb
<h1>RegisteredApplications#new</h1>
<p>Find me in app/views/registered_applications/new.html.erb</p>

<%= form_for @registered_apps do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    </br>

    <div>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>

    </br>

    <div>
      <%= f.submit "Save" %>
    </div>
<% end %>

app/views/registered_applications/show.html.erb
<h1>RegisteredApplications#show</h1>
<p>Find me in app/views/registered_applications/show.html.erb</p>

<h1><%= @registered_apps.title %></h1>

<div>
 <p><%= @registered_apps.url %></p>
</div>


<div>
  <h3>Here are the events associated with this registered app</h3>
  <%= @events.count %>
  <% @events.each do |this_event| %>
    <div>
      <%= this_event %>
    </div>
  <% end %>
</div>

<%= pie_chart @registered_apps.event.group(:name).count %>
<%= line_chart @registered_apps.event.group_by_day(:created_at).count %>

<div class="col-md-4">
  <%= link_to "Back to index", registered_applications_path, class: 'btn btn-primary' %>
  <%= link_to "Edit", edit_registered_application_path(@registered_apps), class: 'btn btn-success' %>
  <%= link_to "Delete Wiki", @registered_apps, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
</div>

 <div class="row">

 </div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>